### ISSUE TITLE
Is there any way for this library to use RPi.GPIO instead of digitalio?

### ISSUE THREAD

**Issue by mytechguyri** [BiffoBear/CircuitPython_AS3935#2]
Its just so limiting, and inefficient to have to constantly poll the device, since digitalio doesn't support interrupts, whereas RPi.GPIO does support interrupts.

**Comment by BiffoBear** [comment]
Hi, thanks for your comment. It is inefficient but the driver is written to run under CircuitPython. CircuitPython does not support interrupts. I have the same issue with packet radio drivers. If you are only going to use it with a Raspberry Pi then feel free to fork the code and and interrupt support.

**Comment by mytechguyri** [comment]
Unfortunately, my coding skills aren't there yet.... But, I think I managed
to get it working to capture the interrupt with RPi.GPIO.... seems I had to
use the dtoverlay in raspberry pi os so that spidev wouldn't have control
of pins 7&8 even though those are the spi pins I'm using.... Since the
hardware is no longer latching into them, I can use this library, and
Rpi.GPIO to handle the interrupt events on the same pins.... Weird, but it
works.
