### ISSUE TITLE
Having problems with false lightning stikes

### ISSUE THREAD

**Issue by Whimick** [BiffoBear/CircuitPython_AS3935#3]
Hi,
Can any one tell me how to set up the driver to reduce false possitives, unfortuntaly my knowledge of python3 is a little limited, I would be greatful for any help.

Michael

**Comment by BiffoBear** [comment]
Hi,

Please have a look at the API documentation on [Read The Docs](https://circuitpython-as3935.readthedocs.io/en/latest/api.html). Particularly the `indoor` property, `noise_floor_limit` property and the `spike_threshold` property. Experiment with different combinations and see if they solve your problem. 

Cheers,
Martin

**Comment by Whimick** [comment]
Thank you for repling.

Unfortunatly my knowledge of programming is limited.

Looking at :
    @property
    def noise_floor_limit(self):
        """int: Get or set the noise floor limit threshold in the range 0 - 7 (default is 2). When
        this threshold is exceeded, an interrupt is issued. Higher values allow operation with
        higher background noise but decrease sensitivity to lightning strikes.
        """
        return self._get_register(self._NF_LEV)

How would I set the set the noise floor limit threshold?
Would you be kind enough to show me an example?
Michael

**Comment by BiffoBear** [comment]
Assuming that you have created a sensor object as in the example code and called it `sensor` then setting properties works like this:
```
>>> sensor.indoor = True
>>> sensor.noise_floor_limit = 4
>>> sensor.spike_threshold = 6
```

Hope that helps.

Cheers,
Martin

**Comment by Whimick** [comment]
Thanks for your help.
Using your as3935_simpletest.py, and adding your examples like below:

sensor = biffobear_as3935.AS3935_I2C(i2c, interrupt_pin=interrupt_pin)
sensor.indoor = True
sensor.noise_floor_limit = 4
sensor.spike_threshold = 6

I hope I've got it right

Michael

**Comment by BiffoBear** [comment]
Hi, that looks fine. I suggest running it with various combinations of values until you find the best solution for you. 

Cheers,
Martin
